### PR TITLE
Added feature to auto-expire task keys in Redis, updated README.md to explain passing options

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pilwon** [comment]
Thanks @exshovelrydr it's a great idea to add ttl support. But I think, for consistent and finer control, it's better to add this option as chainable function to individual task definition rather than the entire `barbeque` instance.

**Comment by pilwon** [comment]
@exshovelrydr Looking at your code more closely I believe you wanted an auto-cleanup feature of a task after processing regardless of the state result it's in. If this is the case I'd call it a `cleanup` because it could confuse with the real task lifespan (time-to-live) control feature. Also it'd be better to only expire the key on success and keep failed tasks alive because that's an important information that you don't want disappeared until you check. Please share your thoughts on this idea.

(reference: http://docs.celeryproject.org/en/latest/configuration.html#celery-task-result-expires)

**Comment by ghost** [comment]
Thank you @pilwon.  First, please let me add some background information on my thought process.

I was loosly referencing 'celery-task-result-expires' from the celery project, which does auto-expire the _result_ of a task.  This is an important distinction as the broker's task is separate from the backend result.  This is set as a global config option to the celery backend.  Furthermore, celery will expire a result regardless of its associated tasks' state.  Please review the code here: https://github.com/celery/celery/blob/master/celery/backends/redis.py

In Barbeque, I like how the task result is stored within the task itself as I do not see the benefit of creating a seperation between the two since only Redis is being used as both the 'broker' and 'backend'.  

My pull request would mark a task for expiration only when the Redis multi() chain was finished in the _stateChangeProcessingToComplete() function.  This would only expire Barbeque tasks marked as completed.  Failed tasks will never have the Redis EXPIRE command called as its part of a different multi() chain under the _stateChangeProcessingToFailed() function.  With having that said, I do not understand your concern expiring failed tasks.

I do understand that you don't want to cause confusion with the task's lifespan and renaming as _cleanup_ is appropriate.  Please let me know if I can be of any more assistance.

**Comment by pilwon** [comment]
@exshovelrydr Silly me. Your clarification made me realize I not only misread the celery reference page but also didn't read my own code properly before commenting. I appreciate your explanation and everything makes sense now. :+1:

You're probably the first person who discovered the `Barbeque` project and actually saw enough value in it for you to try it and contribute w/ PR. I'm curious to learn about your experience so far (i.e. what do you like and don't like, what works and doesn't) and would like your suggestions for the future direction of it.

**Comment by ghost** [comment]
@pilwon Your code base is clean/well-done.

As we know, the strength of Node.js its ability to process I/O quickly using its event-loop, while its weakness is CPU intensive computations.  The single threaded nature of Node.js allows long-running processes to block the event-loop.  The more developers who figure this out will turn to a distributed queue to offload CPU intensive tasks from the main loop to workers.  These tasks may include: image manipulation, eventual consistency to a relational database,  etc. Therefore, I see potential in `Barbeque` to fill this need.  

In the past few days I have used `Barbeque` to process 150,721 tasks with only 10 becoming stuck in processing and that is most likely due to cold shutdowns.  These results are very promising to me.

**Pull request closed without merging**
